services:
  - type: web
    name: house-scorecard-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn house_scorecard.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/browsers
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: false
    plan: free
