# Generated by Django 5.2.4 on 2025-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mustHave', 'Must-Have'), ('niceToHave', 'Nice-to-Have'), ('dealBreaker', 'Deal Breaker')], max_length=20)),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='Importance from 1-10 for Nice-to-Haves')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_type', models.CharField(choices=[('stars', 'Stars (1-5)'), ('yesNo', 'Yes/No'), ('scale10', 'Scale (1-10)')], default='stars', help_text='Only for Nice-to-Haves', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('listing_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('ratings', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
