# Generated by Django 5.2.4 on 2025-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_property_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('viewing_scheduled', 'Viewing Scheduled'), ('viewed', 'Viewed'), ('offer_made', 'Offer Made'), ('under_contract', 'Under Contract'), ('closed', 'Closed'), ('passed', 'Passed')], help_text='Current status in the house hunting pipeline', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status_history',
            field=models.JSONField(blank=True, default=list, help_text='History of status changes with timestamps'),
        ),
    ]
