# Generated by Django 5.2.4 on 2025-08-07 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_user_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Complete AI analysis results'),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_analysis_date',
            field=models.DateTimeField(blank=True, help_text='When AI analysis was performed', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_analysis_summary',
            field=models.TextField(blank=True, help_text='AI analysis summary'),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_buyer_recommendation',
            field=models.CharField(blank=True, help_text='AI buyer recommendation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI analysis confidence (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_overall_grade',
            field=models.CharField(blank=True, help_text='AI overall grade (A-F)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_positive_indicators',
            field=models.JSONField(blank=True, default=list, help_text='AI detected positive indicators'),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_price_assessment',
            field=models.CharField(blank=True, help_text='AI price assessment (fair/high/low)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_red_flags',
            field=models.JSONField(blank=True, default=list, help_text='AI detected red flags'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
