# Generated by Django 5.2.4 on 2025-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_ai_analysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ai_buyer_recommendation',
            field=models.CharField(blank=True, help_text='AI buyer recommendation', max_length=100, null=True),
        ),
    ]
